"""
🍗 GYMBRO High-Protein Recipe Library
20 high-protein meal recipes with full macros, ingredients, and prep instructions.
"""

import random

RECIPES = [
    {
        "name": "Greek Chicken Power Bowl",
        "emoji": "🥙",
        "meal_type": "lunch",
        "prep_time": "25 min",
        "servings": 1,
        "calories": 580,
        "protein_g": 48,
        "carbs_g": 42,
        "fat_g": 22,
        "ingredients": [
            "200g chicken breast, diced",
            "150g cooked brown rice",
            "80g cucumber, diced",
            "60g cherry tomatoes, halved",
            "40g feta cheese, crumbled",
            "30g red onion, sliced",
            "10g olive oil",
            "1 tbsp lemon juice",
            "Oregano, salt & pepper to taste",
        ],
        "instructions": [
            "Season chicken with oregano, salt & pepper. Grill or pan-sear on medium-high for 6-7 min per side until cooked through.",
            "Cook brown rice according to package directions (or use pre-cooked).",
            "Dice cucumber, halve tomatoes, slice red onion.",
            "Assemble bowl: rice base, top with chicken, veggies, and crumbled feta.",
            "Drizzle with olive oil and lemon juice. Toss gently and serve.",
        ],
    },
    {
        "name": "Protein Pancake Stack",
        "emoji": "🥞",
        "meal_type": "breakfast",
        "prep_time": "15 min",
        "servings": 1,
        "calories": 490,
        "protein_g": 42,
        "carbs_g": 48,
        "fat_g": 12,
        "ingredients": [
            "1 scoop (30g) vanilla whey protein",
            "1 banana, mashed",
            "2 whole eggs",
            "40g oats, blended into flour",
            "1 tsp baking powder",
            "50ml almond milk",
            "100g mixed berries (topping)",
            "1 tbsp sugar-free maple syrup",
        ],
        "instructions": [
            "Blend oats into a fine flour. Mix with protein powder and baking powder.",
            "Mash banana in a bowl. Whisk in eggs and almond milk.",
            "Combine wet and dry ingredients until smooth batter forms.",
            "Heat a non-stick pan on medium. Pour ¼ of batter per pancake.",
            "Cook 2 min per side until golden. Stack, top with berries and syrup.",
        ],
    },
    {
        "name": "Spicy Tuna Lettuce Wraps",
        "emoji": "🌮",
        "meal_type": "lunch",
        "prep_time": "10 min",
        "servings": 1,
        "calories": 380,
        "protein_g": 44,
        "carbs_g": 12,
        "fat_g": 18,
        "ingredients": [
            "2 cans (160g drained) tuna in water",
            "1 tbsp sriracha mayo",
            "1 tbsp soy sauce",
            "30g avocado, diced",
            "20g red onion, finely diced",
            "1 tsp sesame oil",
            "4 large butter lettuce leaves",
            "Sesame seeds for garnish",
        ],
        "instructions": [
            "Drain tuna and flake into a bowl.",
            "Mix in sriracha mayo, soy sauce, and sesame oil until well combined.",
            "Fold in diced avocado and red onion.",
            "Spoon the tuna mixture into lettuce cups.",
            "Garnish with sesame seeds. Serve immediately.",
        ],
    },
    {
        "name": "Beef & Broccoli Stir-Fry",
        "emoji": "🥩",
        "meal_type": "dinner",
        "prep_time": "20 min",
        "servings": 1,
        "calories": 520,
        "protein_g": 46,
        "carbs_g": 35,
        "fat_g": 20,
        "ingredients": [
            "200g lean beef sirloin, sliced thin",
            "200g broccoli florets",
            "150g cooked jasmine rice",
            "2 tbsp soy sauce",
            "1 tbsp oyster sauce",
            "1 clove garlic, minced",
            "1 tsp fresh ginger, grated",
            "1 tbsp sesame oil",
            "1 tsp cornstarch + 2 tbsp water",
        ],
        "instructions": [
            "Slice beef thin against the grain. Marinate in 1 tbsp soy sauce for 10 min.",
            "Heat sesame oil in a wok on high heat. Sear beef 2 min, set aside.",
            "Stir-fry broccoli with garlic and ginger for 3 min until bright green.",
            "Return beef. Add oyster sauce, remaining soy sauce, and cornstarch slurry.",
            "Toss until sauce thickens (1 min). Serve over jasmine rice.",
        ],
    },
    {
        "name": "Cottage Cheese Protein Bowl",
        "emoji": "🥣",
        "meal_type": "breakfast",
        "prep_time": "5 min",
        "servings": 1,
        "calories": 420,
        "protein_g": 40,
        "carbs_g": 38,
        "fat_g": 12,
        "ingredients": [
            "250g low-fat cottage cheese",
            "100g mixed berries (blueberries, strawberries)",
            "30g granola (low sugar)",
            "1 tbsp honey",
            "1 tbsp chia seeds",
            "10g sliced almonds",
        ],
        "instructions": [
            "Scoop cottage cheese into a bowl.",
            "Top with mixed berries and granola.",
            "Sprinkle chia seeds and sliced almonds on top.",
            "Drizzle with honey.",
            "Mix lightly or eat layered — ready to eat!",
        ],
    },
    {
        "name": "Turkey Meatball Marinara",
        "emoji": "🍝",
        "meal_type": "dinner",
        "prep_time": "30 min",
        "servings": 1,
        "calories": 560,
        "protein_g": 50,
        "carbs_g": 48,
        "fat_g": 16,
        "ingredients": [
            "200g lean ground turkey",
            "1 egg white",
            "20g breadcrumbs",
            "1 clove garlic, minced",
            "100g whole wheat pasta",
            "120ml marinara sauce (low sugar)",
            "15g parmesan, grated",
            "Fresh basil leaves",
            "Salt, pepper, Italian seasoning",
        ],
        "instructions": [
            "Mix turkey, egg white, breadcrumbs, garlic, and seasonings. Form 8-10 meatballs.",
            "Pan-sear meatballs in a non-stick pan 3-4 min per side until browned.",
            "Add marinara sauce, cover, simmer 10 min until meatballs are cooked through.",
            "Cook whole wheat pasta al dente. Drain and plate.",
            "Top pasta with meatballs and sauce. Finish with parmesan and fresh basil.",
        ],
    },
    {
        "name": "Salmon Avocado Poke Bowl",
        "emoji": "🐟",
        "meal_type": "lunch",
        "prep_time": "15 min",
        "servings": 1,
        "calories": 620,
        "protein_g": 42,
        "carbs_g": 50,
        "fat_g": 26,
        "ingredients": [
            "150g sushi-grade salmon, cubed",
            "150g cooked sushi rice",
            "60g avocado, sliced",
            "50g edamame, shelled",
            "30g cucumber, diced",
            "2 tbsp soy sauce",
            "1 tsp sesame oil",
            "1 tsp rice vinegar",
            "Sesame seeds, nori strips",
        ],
        "instructions": [
            "Cube salmon into bite-size pieces. Toss with soy sauce, sesame oil, and rice vinegar.",
            "Let salmon marinate for 5-10 min in the fridge.",
            "Cook sushi rice and let cool slightly.",
            "Assemble bowl: rice base, arrange salmon, avocado, edamame, and cucumber.",
            "Top with sesame seeds and nori strips. Serve chilled.",
        ],
    },
    {
        "name": "Egg White Veggie Omelette",
        "emoji": "🍳",
        "meal_type": "breakfast",
        "prep_time": "10 min",
        "servings": 1,
        "calories": 340,
        "protein_g": 38,
        "carbs_g": 14,
        "fat_g": 14,
        "ingredients": [
            "6 egg whites (or 200ml liquid egg whites)",
            "1 whole egg",
            "50g spinach",
            "40g bell pepper, diced",
            "30g mushrooms, sliced",
            "20g low-fat cheddar, shredded",
            "Salt, pepper, garlic powder",
            "Cooking spray",
        ],
        "instructions": [
            "Whisk egg whites and whole egg together with salt, pepper, and garlic powder.",
            "Heat a non-stick pan on medium with cooking spray.",
            "Sauté mushrooms and bell pepper for 2-3 min. Add spinach, cook 1 min.",
            "Pour egg mixture over vegetables. Cook 3-4 min until edges set.",
            "Add cheese on one half, fold, cook 1 more minute. Serve immediately.",
        ],
    },
    {
        "name": "Chicken Tikka Masala (Lean)",
        "emoji": "🍛",
        "meal_type": "dinner",
        "prep_time": "35 min",
        "servings": 1,
        "calories": 540,
        "protein_g": 48,
        "carbs_g": 44,
        "fat_g": 18,
        "ingredients": [
            "200g chicken breast, cubed",
            "80g plain Greek yogurt",
            "100g canned crushed tomatoes",
            "150g cooked basmati rice",
            "1 tbsp tikka masala spice blend",
            "1 clove garlic, minced",
            "1 tsp fresh ginger, grated",
            "1 tbsp olive oil",
            "Fresh cilantro for garnish",
        ],
        "instructions": [
            "Marinate chicken in Greek yogurt and half the tikka spice for 15 min (or overnight).",
            "Heat olive oil. Sear chicken on high heat 5-6 min until golden.",
            "Add garlic, ginger, remaining spice. Cook 1 min until fragrant.",
            "Add crushed tomatoes, simmer 10-12 min until sauce thickens.",
            "Serve over basmati rice, garnish with fresh cilantro.",
        ],
    },
    {
        "name": "High-Protein Smoothie Bowl",
        "emoji": "🫐",
        "meal_type": "breakfast",
        "prep_time": "5 min",
        "servings": 1,
        "calories": 440,
        "protein_g": 40,
        "carbs_g": 50,
        "fat_g": 8,
        "ingredients": [
            "1 scoop (30g) chocolate whey protein",
            "1 frozen banana",
            "100g frozen mixed berries",
            "100ml unsweetened almond milk",
            "1 tbsp peanut butter powder (PB2)",
            "20g granola (topping)",
            "1 tbsp chia seeds (topping)",
            "Fresh berries for topping",
        ],
        "instructions": [
            "Blend protein powder, frozen banana, frozen berries, almond milk, and PB2 until thick and smooth.",
            "Pour into a bowl — it should be thicker than a drinkable smoothie.",
            "Top with granola, chia seeds, and fresh berries.",
            "Eat immediately with a spoon. Enjoy!",
        ],
    },
    {
        "name": "Shrimp & Quinoa Fiesta",
        "emoji": "🦐",
        "meal_type": "lunch",
        "prep_time": "20 min",
        "servings": 1,
        "calories": 480,
        "protein_g": 44,
        "carbs_g": 46,
        "fat_g": 14,
        "ingredients": [
            "200g shrimp, peeled & deveined",
            "120g cooked quinoa",
            "60g black beans, drained",
            "50g corn kernels",
            "40g red bell pepper, diced",
            "30g red onion, diced",
            "Juice of 1 lime",
            "1 tsp cumin, 1 tsp paprika",
            "Cilantro, salt & pepper",
        ],
        "instructions": [
            "Season shrimp with cumin, paprika, salt & pepper.",
            "Sear shrimp in a hot pan 2-3 min per side until pink and curled.",
            "Cook quinoa according to package (or use pre-cooked).",
            "Mix quinoa, black beans, corn, bell pepper, and red onion in a bowl.",
            "Top with shrimp, squeeze lime juice, garnish with cilantro.",
        ],
    },
    {
        "name": "Lean Steak Burrito Bowl",
        "emoji": "🥩",
        "meal_type": "dinner",
        "prep_time": "25 min",
        "servings": 1,
        "calories": 590,
        "protein_g": 46,
        "carbs_g": 52,
        "fat_g": 20,
        "ingredients": [
            "180g flank steak",
            "150g cooked brown rice",
            "60g black beans, rinsed",
            "50g salsa",
            "40g avocado, sliced",
            "30g corn kernels",
            "20g low-fat sour cream",
            "1 tsp chili powder, 1 tsp cumin",
            "Lime wedge, cilantro",
        ],
        "instructions": [
            "Rub steak with chili powder, cumin, salt & pepper.",
            "Grill or pan-sear on high heat 4-5 min per side for medium (adjust for preference).",
            "Rest steak 5 min, then slice thin against the grain.",
            "Assemble bowl: rice, beans, corn, then sliced steak on top.",
            "Add salsa, avocado, sour cream. Squeeze lime, add cilantro.",
        ],
    },
    {
        "name": "Baked Cod with Sweet Potato",
        "emoji": "🐠",
        "meal_type": "dinner",
        "prep_time": "30 min",
        "servings": 1,
        "calories": 460,
        "protein_g": 44,
        "carbs_g": 40,
        "fat_g": 12,
        "ingredients": [
            "200g cod fillet",
            "200g sweet potato, cubed",
            "100g green beans",
            "1 tbsp olive oil",
            "1 clove garlic, minced",
            "Juice of ½ lemon",
            "1 tsp paprika",
            "Fresh dill, salt & pepper",
        ],
        "instructions": [
            "Preheat oven to 200°C (400°F). Toss sweet potato cubes in ½ tbsp olive oil, paprika, salt.",
            "Roast sweet potato for 15 min on a baking tray.",
            "Season cod with garlic, lemon juice, dill, salt & pepper. Place on tray with sweet potato.",
            "Add green beans to the tray. Drizzle remaining olive oil.",
            "Bake 12-15 min until cod flakes easily. Serve immediately.",
        ],
    },
    {
        "name": "Chicken Caesar Protein Wrap",
        "emoji": "🌯",
        "meal_type": "lunch",
        "prep_time": "10 min",
        "servings": 1,
        "calories": 480,
        "protein_g": 46,
        "carbs_g": 32,
        "fat_g": 18,
        "ingredients": [
            "180g grilled chicken breast, sliced",
            "1 large whole wheat tortilla",
            "40g romaine lettuce, chopped",
            "20g parmesan, shaved",
            "2 tbsp light Caesar dressing",
            "Cherry tomatoes, halved",
            "Croutons (optional, 15g)",
        ],
        "instructions": [
            "Grill or use pre-cooked chicken breast. Slice thin.",
            "Warm tortilla in a dry pan for 30 seconds to make it pliable.",
            "Spread Caesar dressing down the center of the tortilla.",
            "Layer lettuce, chicken, parmesan, tomatoes, and croutons.",
            "Fold bottom up, then roll tightly from one side. Slice in half diagonally.",
        ],
    },
    {
        "name": "Tofu & Vegetable Stir-Fry",
        "emoji": "🥬",
        "meal_type": "dinner",
        "prep_time": "20 min",
        "servings": 1,
        "calories": 440,
        "protein_g": 36,
        "carbs_g": 38,
        "fat_g": 16,
        "ingredients": [
            "250g extra-firm tofu, pressed & cubed",
            "150g cooked brown rice",
            "100g mixed stir-fry vegetables (bell pepper, snap peas, carrots)",
            "2 tbsp soy sauce",
            "1 tbsp hoisin sauce",
            "1 tsp sesame oil",
            "1 clove garlic, minced",
            "1 tsp fresh ginger",
            "Sesame seeds, green onion",
        ],
        "instructions": [
            "Press tofu for 15 min (or use pre-pressed). Cut into cubes.",
            "Heat sesame oil on high. Pan-fry tofu 3-4 min per side until golden and crispy.",
            "Remove tofu. Stir-fry vegetables with garlic and ginger for 3-4 min.",
            "Return tofu to pan. Add soy sauce and hoisin, toss to coat.",
            "Serve over brown rice. Garnish with sesame seeds and green onion.",
        ],
    },
    {
        "name": "Overnight Protein Oats",
        "emoji": "🫙",
        "meal_type": "breakfast",
        "prep_time": "5 min (+ overnight)",
        "servings": 1,
        "calories": 460,
        "protein_g": 38,
        "carbs_g": 52,
        "fat_g": 12,
        "ingredients": [
            "60g rolled oats",
            "1 scoop (30g) vanilla whey protein",
            "150ml unsweetened almond milk",
            "100g Greek yogurt",
            "1 tbsp chia seeds",
            "1 tbsp peanut butter",
            "½ banana, sliced (topping)",
            "1 tsp honey (optional)",
        ],
        "instructions": [
            "Mix oats, protein powder, almond milk, Greek yogurt, and chia seeds in a jar.",
            "Stir well to combine — make sure there are no protein powder lumps.",
            "Seal jar and refrigerate overnight (at least 6 hours).",
            "In the morning, stir. Top with peanut butter, banana slices, and honey.",
            "Eat cold straight from the jar. Perfect for grab-and-go!",
        ],
    },
    {
        "name": "Chicken Sausage Stuffed Peppers",
        "emoji": "🫑",
        "meal_type": "dinner",
        "prep_time": "35 min",
        "servings": 2,
        "calories": 420,
        "protein_g": 40,
        "carbs_g": 30,
        "fat_g": 16,
        "ingredients": [
            "200g chicken sausage, casings removed",
            "3 large bell peppers, halved & seeded",
            "100g cooked quinoa",
            "60g canned black beans, rinsed",
            "40g corn kernels",
            "50g salsa",
            "30g low-fat mozzarella, shredded",
            "1 tsp cumin, 1 tsp garlic powder",
            "Fresh cilantro",
        ],
        "instructions": [
            "Preheat oven to 190°C (375°F). Halve peppers, remove seeds, place cut-side up on a baking tray.",
            "Cook chicken sausage in a pan, breaking it apart, until browned (5-6 min).",
            "Mix cooked sausage with quinoa, black beans, corn, salsa, cumin & garlic powder.",
            "Stuff each pepper half generously. Top with shredded mozzarella.",
            "Bake 20-25 min until peppers are tender and cheese is melted. Garnish with cilantro.",
        ],
    },
    {
        "name": "Tuna & White Bean Salad",
        "emoji": "🥗",
        "meal_type": "lunch",
        "prep_time": "10 min",
        "servings": 1,
        "calories": 440,
        "protein_g": 48,
        "carbs_g": 30,
        "fat_g": 14,
        "ingredients": [
            "2 cans (160g drained) tuna in water",
            "100g canned white beans (cannellini), drained",
            "60g cherry tomatoes, halved",
            "40g red onion, thinly sliced",
            "30g arugula",
            "1 tbsp olive oil",
            "1 tbsp red wine vinegar",
            "1 tsp Dijon mustard",
            "Salt, pepper, Italian herbs",
        ],
        "instructions": [
            "Drain tuna and white beans. Add to a large bowl.",
            "Add halved cherry tomatoes, sliced red onion, and arugula.",
            "Whisk olive oil, red wine vinegar, Dijon mustard, and seasonings for the dressing.",
            "Pour dressing over salad and toss gently to combine.",
            "Serve immediately or refrigerate for a cold packed lunch.",
        ],
    },
    {
        "name": "Protein Lava Mug Cake",
        "emoji": "🍫",
        "meal_type": "snack",
        "prep_time": "5 min",
        "servings": 1,
        "calories": 320,
        "protein_g": 32,
        "carbs_g": 28,
        "fat_g": 8,
        "ingredients": [
            "1 scoop (30g) chocolate whey protein",
            "1 egg",
            "2 tbsp cocoa powder",
            "1 tbsp flour (or oat flour)",
            "3 tbsp almond milk",
            "1 tsp baking powder",
            "1 tbsp sugar-free chocolate chips",
            "Pinch of salt",
        ],
        "instructions": [
            "Mix all dry ingredients (protein, cocoa, flour, baking powder, salt) in a large mug.",
            "Add egg and almond milk. Stir until smooth batter forms.",
            "Drop chocolate chips into the center (they'll create the lava).",
            "Microwave on high for 70-90 seconds. Center should be slightly gooey.",
            "Let cool 1 min. Eat straight from the mug — careful, it's hot!",
        ],
    },
    {
        "name": "Korean BBQ Chicken Lettuce Cups",
        "emoji": "🍗",
        "meal_type": "dinner",
        "prep_time": "20 min",
        "servings": 1,
        "calories": 460,
        "protein_g": 46,
        "carbs_g": 28,
        "fat_g": 18,
        "ingredients": [
            "200g chicken thigh (boneless, skinless), diced",
            "2 tbsp gochujang (Korean chili paste)",
            "1 tbsp soy sauce",
            "1 tbsp honey",
            "1 tsp sesame oil",
            "1 clove garlic, minced",
            "4-6 butter lettuce leaves",
            "Pickled carrots & daikon (quick pickle)",
            "Sesame seeds, green onion",
        ],
        "instructions": [
            "Mix gochujang, soy sauce, honey, sesame oil, and garlic into a sauce.",
            "Dice chicken thigh. Toss with half the sauce and marinate 10 min.",
            "Cook chicken on medium-high heat 6-7 min until caramelized and cooked through.",
            "Quick pickle: julienne carrots & daikon, toss with rice vinegar + pinch of sugar for 10 min.",
            "Spoon chicken into lettuce cups, top with pickled veggies, sesame seeds, and green onion.",
        ],
    },
]


_last_served = -1  # track last index to avoid repeats


def get_random_recipe() -> dict:
    """Return a random recipe, avoiding back-to-back repeats."""
    global _last_served
    choices = list(range(len(RECIPES)))
    if _last_served >= 0 and len(choices) > 1:
        choices.remove(_last_served)
    idx = random.choice(choices)
    _last_served = idx
    recipe = RECIPES[idx].copy()
    recipe["recipe_number"] = idx + 1
    recipe["total_recipes"] = len(RECIPES)
    return recipe
